# conda env create -f environment.yml
# conda activate wildscenes
### install mmcv from source
## git clone https://github.com/open-mmlab/mmcv.git
## cd mmcv 
## git checkout ea53ed0
## python setup.py install 
name: wildscenes
channels:
  - nvidia/label/cuda-12.1.0
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - binutils=2.40=h1680402_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - cccl=2.3.2=h2c7f797_0
  - cuda=12.1.0=0
  - cuda-cccl=12.4.127=h06a4308_2
  - cuda-cccl_linux-64=12.4.127=h06a4308_2
  - cuda-command-line-tools=12.4.1=h06a4308_1
  - cuda-compiler=12.4.1=h6a678d5_1
  - cuda-crt-dev_linux-64=12.4.131=h06a4308_0
  - cuda-crt-tools=12.4.131=h06a4308_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart-dev=12.4.127=h99ab3db_0
  - cuda-cudart-dev_linux-64=12.4.127=hd681fbe_0
  - cuda-cudart-static=12.4.127=h99ab3db_0
  - cuda-cudart-static_linux-64=12.4.127=hd681fbe_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cuobjdump=12.4.127=h6a678d5_1
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-cupti-dev=12.4.127=h6a678d5_1
  - cuda-cuxxfilt=12.4.127=h6a678d5_1
  - cuda-demo-suite=12.1.55=0
  - cuda-driver-dev=12.4.127=h99ab3db_0
  - cuda-driver-dev_linux-64=12.4.127=hd681fbe_0
  - cuda-gdb=12.4.127=h122497a_1
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-libraries-dev=12.4.1=h06a4308_1
  - cuda-nsight=12.4.127=h06a4308_1
  - cuda-nvcc=12.4.131=h02f8991_0
  - cuda-nvcc-dev_linux-64=12.4.131=h4ee8466_0
  - cuda-nvcc-impl=12.4.131=h99ab3db_0
  - cuda-nvcc-tools=12.4.131=h99ab3db_0
  - cuda-nvcc_linux-64=12.4.131=he92618c_0
  - cuda-nvdisasm=12.4.127=h6a678d5_1
  - cuda-nvml-dev=12.4.127=h6a678d5_1
  - cuda-nvprof=12.4.127=h6a678d5_1
  - cuda-nvprune=12.4.127=h6a678d5_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvrtc-dev=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-nvvm-dev_linux-64=12.4.131=h06a4308_0
  - cuda-nvvm-impl=12.4.131=h6a678d5_0
  - cuda-nvvm-tools=12.4.131=h6a678d5_0
  - cuda-nvvp=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-opencl-dev=12.4.127=h6a678d5_0
  - cuda-profiler-api=12.4.127=h06a4308_1
  - cuda-runtime=12.4.1=hb982923_0
  - cuda-sanitizer-api=12.4.127=h99ab3db_1
  - cuda-toolkit=12.4.1=hb982923_0
  - cuda-tools=12.4.1=h06a4308_1
  - cuda-version=12.4=hbda6634_3
  - cuda-visual-tools=12.4.1=h06a4308_1
  - dbus=1.13.18=hb2f20db_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.13.3=h4a9f257_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gds-tools=1.9.1.3=h99ab3db_1
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - icu=73.1=h6a678d5_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=12.4.5.8=h99ab3db_1
  - libcublas-dev=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufft-dev=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcufile-dev=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurand-dev=10.3.5.147=h99ab3db_1
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusolver-dev=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libcusparse-dev=12.3.1.170=h99ab3db_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnpp=12.2.5.30=h99ab3db_1
  - libnpp-dev=12.2.5.30=h99ab3db_1
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvfatbin-dev=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjitlink-dev=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libnvjpeg-dev=12.3.1.117=h06a4308_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - ncurses=6.4=h6a678d5_0
  - nsight-compute=2024.1.1.4=h968f9c8_2
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openssl=3.0.16=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.2
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - asttokens==3.0.0
      - attrs==25.3.0
      - black==25.1.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colorama==0.4.6
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.2
      - crcmod==1.7
      - cryptography==45.0.2
      - cycler==0.12.1
      - dash==3.0.4
      - decorator==5.2.1
      - descartes==1.1.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.14.0
      - fire==0.7.0
      - flake8==7.2.0
      - flask==3.0.3
      - fonttools==4.58.0
      - fsspec==2025.5.0
      - ftfy==6.3.1
      - grpcio==1.71.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - ipython==8.36.0
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.5.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - lyft-dataset-sdk==0.0.8
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mmdet==3.0.0
      - mmdet3d==1.4.0
      - mmengine==0.10.7
      - mmsegmentation==1.2.2
      - model-index==0.1.11
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - narwhals==1.40.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==1.26.4
      - nuscenes-devkit==1.1.11
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.41
      - nvidia-nvtx-cu12==12.1.105
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - plotly==6.1.1
      - pluggy==1.6.0
      - plyfile==1.1
      - prettytable==3.16.0
      - prompt-toolkit==3.0.51
      - protobuf==6.31.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.8
      - pycodestyle==2.13.0
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pyflakes==3.3.2
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.28.2
      - retrying==1.3.4
      - rich==13.4.2
      - rpds-py==0.25.0
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - setuptools==60.2.0
      - shapely==1.8.5.post1
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - terminaltables==3.1.10
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tomli==2.2.1
      - torch==2.2.0
      - torchvision==0.17.0
      - tqdm==4.65.2
      - traitlets==5.14.3
      - trimesh==4.6.10
      - triton==2.2.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==1.26.20
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - yapf==0.43.0
      - zipp==3.21.0
